### ISSUE TITLE
Autocomplete is missing some items

### ISSUE THREAD

**Issue by Yo-L-B** [grame-cncm/faustide#37]
Hi!
As the title said, autocomplete doesn't use the full current library for suggestions which is only a minor annoyance for such a great tool that otherwise provides everything needed to get hooked to Faust.

As an example, typing _"co."_ currently suggests:
- co.compression_gain_mono
- co.compressor_lad_mono
- co.compressor_mono
- co.compressor_stereo
- co.limiter_1176_R4_mono
- co.limiter_1176_R4_stereo
- co.limiter_lad_N

and misses:
- peak_compression_gain_mono
- peak_compression_gain_N_chan
- FFcompressor_N_chan
- FBcompressor_N_chan
- FFFBcompressor_N_chan
- RMS_compression_gain_mono
- RMS_compression_gain_N_chan
- RMS_FFFBcompressor_N_chan
- RMS_FBcompressor_peak_limiter_N_chan

From what I've seen and understood, autocomplete relies on _https://faustlibraries.grame.fr/libs/_ (in _/src/monaco-faust/FaustLang.ts_) but I don't get why it can't find those missing items.

I've tried both the online version and a compiled version without luck.

Best Regards

**Comment by Fr0stbyteR** [comment]
Thank you for your remark, I believe that it's due to some empty lines between the documentation in this library, typically
https://github.com/grame-cncm/faustlibraries/blob/56f81f383dfa555dbcd27afc22f0a146819291e7/compressors.lib#L71
This will fail the parse of the documentation for those functions in the IDE.
I suggest to remove the empty lines or prepend them with `//`
cc @sletz

**Comment by Fr0stbyteR** [comment]
Some of the docs are not closing with `//----`
PR created to fix them
https://github.com/grame-cncm/faustlibraries/pull/72

**Comment by Fr0stbyteR** [comment]
now should be able to parse them with https://github.com/grame-cncm/faustide/pull/38

**Comment by sletz** [comment]
Fixed on the deployed https://faustide.grame.fr/.
